# Generated by Django 5.0.4 on 2024-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('salad', 'Salad'), ('snack', 'Snack'), ('lunch', 'Lunch'), ('drink', 'Drink'), ('vegeterian', 'Vegeterian')], max_length=20),
        ),
    ]
