# Generated by Django 5.0.4 on 2024-05-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Salad', 'Salad'), ('Snack', 'Snack'), ('Drink', 'Drink'), ('Soup', 'Soup'), ('Vegeterian', 'Vegeterian')], max_length=20),
        ),
    ]
