# Generated by Django 5.0.4 on 2024-05-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Salad', 'Salad'), ('Snack', 'Snack'), ('Drink', 'Drink'), ('Soup', 'Soup'), ('Vegeterian', 'Vegeterian')], max_length=50),
        ),
    ]
